spring:
  application:
    name: 'auth-app'
  datasource:
    url: jdbc:h2:mem:testdb # Persistent File-Based Database
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
#        enabled: true
        path: /h2-console
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 704768179927-vt1rcus7oaqs5dk4jiva9dm62j9aj2pv.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
zoom:
  api:
    oauth-url: https://zoom.us/oauth
    base-url: https://api.zoom.us/v2
    account-id: ob_ghwb4SMyvO9zPYPScEA
    client-id: iTgzd8_3SEm3MxrohFVUWg
    client-secret: DPjYGa2fGWsHokklY9uDhVd5T3CCL3ZN

jwt:
  secret-key: Qlg3eCFRM3QkVzl6I0MybSpQNXZARThyJks0eV5HNmo= # Base64(BX7x!Q3t$W9z#C2m*P5v@E8r&K4y^G6j)
  access-token-validity: 1800000 # 30 minutes in milliseconds (30 * 60 * 1000)
  refresh-token-validity: 604800000  # 7 days in milliseconds (7 * 24 * 60 * 60 * 1000)

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.security.oauth2: DEBUG
#    org.springframework.security.web.authentication: DEBUG
#    org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter: DEBUG
